<footer class="footer">
  <div class="foo_top">
    <div class="inner">
      <p class="foo_logo"><span class="a11y">모두의유언</span></p>
      <div class="foo_link">
        <a href="#">모두의 유언 이용 약관</a>
        <a href="#">개인정보 처리 방침</a>
        <span>감수 : 법무법인 모두의 법률</span>
      </div>
    </div>
  </div>
  <div class="foo_btm">
    <div class="inner">
      <p>(주)식스맨팩토리</p>
      <div class="addr">
        <span>대표 : 정희원</span>
        <span>사업자정보 : 105-87-84378</span>
        <p>서울특별시 강남구 학동로 42길 21, 3층</p>
      </div>
      <p class="copyr">Copyright ©sixmanfactory. All right reserved.</p>
    </div>
  </div>
</footer>

<script src="@@webroot/assets/js/swiper-bundle.min.js"></script>
<script src="@@webroot/assets/js/ui.js"></script>
