<header id="header" class="header @@headertype">
	<div class="inner">
		<h1 class="logo"><span class="a11y">every say - 모두의 유언</span></h1>

		<div class="gnb">
			<ul>
				<li><a href="#">간편 유언장</a></li>
				<li><a href="#">프리미엄 유언장</a></li>
				<li><a href="#">서비스 소개</a></li>
				<li><a href="#">고객센터</a></li>
			</ul>
		</div>

		<div class="util">
			<!-- 로그인 전 -->
			<div>
				<a href="#" class="btn_join">회원가입</a>
				<a href="#" class="btn_login">로그인</a>
			</div>
			<!-- 로그인 전 -->
			<div>

			</div>
		</div>
	</div>
</header>