<header id="header" class="header @@headertype">
	<div class="inner">
		<h1 class="logo"><span class="a11y">every say - 모두의 유언</span></h1>

		<div class="gnb">
			<ul>
				<li><a href="/everysay/simple/simple_step01.html">간편 유언장</a></li>
				<li><a href="/everysay/premium/premium_step01.html">프리미엄 유언장</a></li>
				<li><a href="#">서비스 소개</a></li>
				<li><a href="/everysay/customer/faq.html">고객센터</a></li>
			</ul>
		</div>

		<div class="util">
			<!-- 로그인 전 -->
			<div>
				<a href="/everysay/member/join01.html" class="btn_join">회원가입</a>
				<a href="/everysay/member/login.html" class="btn_login">로그인</a>
			</div>
			<!-- 로그인 후 -->
			<!-- <div class="user_info">
				<i class="user" style="background-image: url('/assets/images/common/user_icon.png');"></i>
				김유민 <span>님</span>
			</div> -->
		</div>
	</div>
</header>