<header id="header" class="header @@headertype">
	<div class="inner">
		<h1 class="logo"><span class="a11y">every say - 모두의 유언</span></h1>
		<a href="#" id="btn_mmenu" class="btn_mmenu"><span class="a11y">모바일 메뉴 열기</span></a>
		<div class="gnb">
			<ul>
				<li><a href="/everysay/simple/simple_step01.html">간편 유언장</a></li>
				<li><a href="/everysay/premium/premium_step01.html">프리미엄 유언장</a></li>
				<li><a href="#">서비스 소개</a></li>
				<li><a href="/everysay/customer/faq.html">고객센터</a></li>
			</ul>
		</div>

		<div class="util">
			<!-- 로그인 전 -->
			<!-- <div>
				<a href="/everysay/member/join01.html" class="btn_join">회원가입</a>
				<a href="/everysay/member/login.html" class="btn_login">로그인</a>
			</div> -->
			<!-- 로그인 후 -->
			<div class="user_info">
				<i class="user" style="background-image: url('/assets/images/common/user_icon.png');"></i>
				김유민 <span>님</span>
			</div>
		</div>
		<div class="mobile_menu">
			<div class="m_inner">
				<a href="#" id="btn_mmenu_close" class="btn_mmenu_close"><span class="a11y">모바일 메뉴 닫기</span></a>
				<div class="m_gnb">
					<ul>
						<li><a href="/everysay/simple/simple_step01.html">간편 유언장</a></li>
						<li><a href="/everysay/premium/premium_step01.html">프리미엄 유언장</a></li>
						<li><a href="#">서비스 소개</a></li>
						<li><a href="/everysay/customer/faq.html">고객센터</a>
							<div class="m_sub_gnb">
								<p><a href="#">자주 묻는 질문</a></p>
								<p><a href="#">1:1 문의</a></p>
							</div>
						</li>
						<li><a href="/everysay/mypage/mypage01.html">마이페이지</a>
							<div class="m_sub_gnb">
								<p><a href="#">가입정보 확인</a></p>
								<p><a href="#">내 유언장</a></p>
							</div>
						</li>
						<li>
							<p class="m_etc_link"><a href="#">모두의 유언장 이용 약관</a></p>
							<p class="m_etc_link"><a href="#">개인정보 처리 방침</a></p>

							<a href="#" class="btn_mlogut"><span>로그아웃</span></a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</header>