<!DOCTYPE html>
<html lang="ko_KR">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="keywords" content="모두의 유언, 유언장, every say"/>
  <meta name="description" content="꼭 남기고 싶은 말이 있으신가요? 모두의 유언에서 가족과 친구들에게 이야기를 남길 수 있어요."/>  
  <meta property="og:locale" content="ko_KR" />
  <meta property="og:type" content="website" />
  <meta property="og:title" content="everysay" />
  <meta property="og:keywords" content="everysay" />
  <meta property="og:description" content="꼭 남기고 싶은 말이 있으신가요? 모두의 유언에서 가족과 친구들에게 이야기를 남길 수 있어요." />
  <meta property="og:url" content="@" />
  <!-- <meta property="og:image" content="@@webroot/assets/images/common/sns_share.jpg"> -->
  <meta property="og:site_name" content="everysay" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:description" content="꼭 남기고 싶은 말이 있으신가요? 모두의 유언에서 가족과 친구들에게 이야기를 남길 수 있어요." />
  <meta name="twitter:title" content="everysay" />
  <!-- <link rel="icon" href="@@webroot/assets/images/common/favicon.png" sizes="32x32" /> -->
  
	<title>모두의 유언 @@pagetitle</title>
  <script src="@@webroot/assets/js/jquery-3.6.0.min.js"></script>
	<link rel="stylesheet" href="@@webroot/assets/css/ui.css">